# -*- coding: utf-8 -*-
"""Numpy2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LefrPlEbYKf11rzl4x2D_U3Ipa_DiX8m
"""

import numpy as np

A = np.array([1,2,3,4,5,6])
B = np.reshape(A, (2, 3))
B

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

x = np.array((3,5,7))
 y = np.array((5,7,9))
 np.hstack((x,y))

a = np.array([[1,2,3],[4,5,6]])
a.flatten()

b = np.array([1,2,3, 4,5,6])
b.flatten()

b = np.array([1,2,3, 4,5,6])
np.reshape(b, (-1, 2))

x = np.random.random((5,5))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

arr = np.random.randint(30, size= (5,6))
arr.mean()

arr = np.random.randint(30, size= (5,6))
arr.std()

arr = np.random.randint(30, size= (5,6))
np.median(arr)

arr = np.random.randint(30, size= (5,6))
np.transpose(arr)

n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 
np.trace(n_array)

n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 
np.linalg.det(n_array)

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(arr, 5))
print(np.percentile(arr, 95))

arr = np.empty((3,3))
arr[:] = np.NaN
np.isnan(np.sum(arr))